### ISSUE TITLE
FTDI pins

### ISSUE THREAD

**Issue by SkyJetty** [drolsen/r2-periscope-lighting#31]
The back PCB needs 2 more holes to fit the full 6 pin FTDI cable attachment header on the Pro Mini.   I had to modify my FTDI cable to programed this instead of just plugging it in like I have on every other pro mini ever used...   Add 2 more holes so the 6 pin header will fit.

**Comment by drolsen** [comment]
I've included the two missing pins for a wider range of FTDI adapter compatibility.
Changes are part of release 1.4.1

Thanks!
