### ISSUE TITLE
Errors while ordering Periscope Lighting Kit

### ISSUE THREAD

**Issue by GalaxyGuy4** [drolsen/r2-periscope-lighting#32]
First off all, thanks for having these available. 

Following your step by step procedure to order the boards, I ran into an issue with 2 of the 3 line items on the BOM. See attached screenshot for errors presented during BOM page. 

Steps followed:
https://github.com/drolsen/r2-periscope-lighting/wiki/Ordering-PCBs

![OrderLightKit_JLCPCB](https://github.com/drolsen/r2-periscope-lighting/assets/154478593/972c16f6-c66f-44f7-a5f6-aaca185e5ce2)

Thanks,

**Comment by drolsen** [comment]
Both caps and resistor suppliers went dry.
I've updated the files to include more readily available suppliers for these two components under release 1.4.1.

Please note: As seen in the screenshot above, you do have the option to search for alternatives on out of stock components (search icon on each line item). However I understand this process is suppose to be made as simple as possible, so I'll do my best to keep on top of components as time goes on.

Thanks!
